apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: team-ems209
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ems209_backend:latest
          imagePullPolicy: always
          ports:
            - protocol: TCP
            - containerPort: 5000
      