FROM node:18

# Create app directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci --frozen-lockfile

# Copy the rest of the backend files
COPY . .

# Expose the backend port
EXPOSE 5000

# Start the app
CMD ["npm", "start"]
